import Dict from "../classes/Dict";

const createABZeusDict = () => {
  const dictionary = Dict.getInstance();
  dictionary.l("es");

  dictionary.c("eto|+><", "es", "");
  dictionary.c("suj|+><", "es", "desde ");
  dictionary.c("obj|+><", "es", "hacia ");
  dictionary.c("*.*|+><", "es", "lo contenido en ");

  dictionary.c("eto|+<>", "es", "");
  dictionary.c("suj|+<>", "es", ", que es ");
  dictionary.c("obj|+<>", "es", "hasta ");
  dictionary.c("*.*|+<>", "es", "lo contenido en ");

  dictionary.c("eto|<+>", "es", "es ");
  dictionary.c("suj|<+>", "es", "desde ");
  dictionary.c("obj|<+>", "es", "hacia ");
  dictionary.c("*.*|<+>", "es", "lo contenido en ");

  dictionary.c("a", "es", "una definición inicial vínculante u origen");
  dictionary.c("b", "es", "una conclusión");
  dictionary.c("c", "es", "un contenido o contenedor");
  dictionary.c("d", "es", "el pensamiento");
  dictionary.c("e", "es", "una representación");
  dictionary.c("f", "es", "el momentum de la información");
  dictionary.c("g", "es", "la magnitud logarítmica de la información");
  dictionary.c("h", "es", "dentro o entre");
  dictionary.c("i", "es", "una descripción");
  dictionary.c("j", "es", "un vínculo");
  dictionary.c("k", "es", "la divergencia de la información");
  dictionary.c("l", "es", "la dirección");
  dictionary.c("m", "es", "la pluralidad");
  dictionary.c("n", "es", "un modelo o conjunto singular");
  dictionary.c("o", "es", "lo definido");
  dictionary.c("p", "es", "una proyección");
  dictionary.c("q", "es", "lo previo");
  dictionary.c("r", "es", "una extensión o radio");
  dictionary.c("s", "es", "la oscilación ");
  dictionary.c("t", "es", "lo que existe");
  dictionary.c("u", "es", "una racionalización");
  dictionary.c("v", "es", "una porción");
  dictionary.c("w", "es", "todo");
  dictionary.c("x", "es", "aquí");
  dictionary.c("y", "es", "una descripción racional");
  dictionary.c("z", "es", "un límite de magnitud");
  dictionary.c("á", "es", "la proyección de un origen");
  dictionary.c("é", "es", "la proyección de una representación");
  dictionary.c("í", "es", "la proyección de una descripción");
  dictionary.c("ó", "es", "la proyección de una definición");
  dictionary.c("ú", "es", "una proyección racional");
  dictionary.c("ñ", "es", "un modelo o conjunto oscilante");

  dictionary.c("A", "es", "una definición inicial vínculante u origen");
  dictionary.c("B", "es", "una conclusión");
  dictionary.c("C", "es", "un contenido o contenedor");
  dictionary.c("D", "es", "el pensamiento");
  dictionary.c("E", "es", "una representación");
  dictionary.c("F", "es", "el momentum de la información");
  dictionary.c("G", "es", "la magnitud logarítmica de la información");
  dictionary.c("H", "es", "dentro o entre");
  dictionary.c("I", "es", "una descripción");
  dictionary.c("J", "es", "un vínculo");
  dictionary.c("K", "es", "la divergencia de la información");
  dictionary.c("L", "es", "la dirección");
  dictionary.c("M", "es", "la pluralidad");
  dictionary.c("N", "es", "un modelo o conjunto singular");
  dictionary.c("O", "es", "lo definido");
  dictionary.c("P", "es", "una proyección");
  dictionary.c("Q", "es", "lo previo");
  dictionary.c("R", "es", "una extensión o radio");
  dictionary.c("S", "es", "una oscilación ");
  dictionary.c("T", "es", "lo que existe");
  dictionary.c("U", "es", "una racionalización");
  dictionary.c("V", "es", "una porción");
  dictionary.c("W", "es", "todo");
  dictionary.c("X", "es", "aquí");
  dictionary.c("Y", "es", "una descripción racional");
  dictionary.c("Z", "es", "un límite de magnitud");
  dictionary.c("Á", "es", "la proyección de un origen");
  dictionary.c("É", "es", "la proyección de una representación");
  dictionary.c("Í", "es", "la proyección de una descripción");
  dictionary.c("Ó", "es", "la proyección de una definición");
  dictionary.c("Ú", "es", "una proyección racional");
  dictionary.c("Ñ", "es", "un modelo o conjunto oscilante");

  dictionary.l("en");

  dictionary.c("eto|+><", "en", "");
  dictionary.c("suj|+><", "en", "from ");
  dictionary.c("obj|+><", "en", "towards ");
  dictionary.c("*.*|+><", "en", "contained in ");

  dictionary.c("eto|+<>", "en", "");
  dictionary.c("suj|+<>", "en", "that is from ");
  dictionary.c("obj|+<>", "en", "to ");
  dictionary.c("*.*|+<>", "en", "what is contained in ");

  dictionary.c("eto|<+>", "en", "is ");
  dictionary.c("suj|<+>", "en", "from ");
  dictionary.c("obj|<+>", "en", "towards ");
  dictionary.c("*.*|<+>", "en", "what is contained in ");

  dictionary.c("a", "en", "an initial definition or origin");
  dictionary.c("b", "en", "conclusion");
  dictionary.c("c", "en", "a content or container");
  dictionary.c("d", "en", "a thought");
  dictionary.c("e", "en", "a representation");
  dictionary.c("f", "en", "the momentum of information");
  dictionary.c("g", "en", "the logarithmic magnitude of information");
  dictionary.c("h", "en", "within or between");
  dictionary.c("i", "en", "a description");
  dictionary.c("j", "en", "a link");
  dictionary.c("k", "en", "the divergence of information");
  dictionary.c("l", "en", "a direction");
  dictionary.c("m", "en", "the plurality");
  dictionary.c("n", "en", "a singular model or set");
  dictionary.c("o", "en", "a definition");
  dictionary.c("p", "en", "a projection");
  dictionary.c("q", "en", "the previous");
  dictionary.c("r", "en", "an extension or radius");
  dictionary.c("s", "en", "oscillation ");
  dictionary.c("t", "en", "what exists");
  dictionary.c("u", "en", "a rationalization");
  dictionary.c("v", "en", "a portion");
  dictionary.c("w", "en", "everything");
  dictionary.c("x", "en", "here");
  dictionary.c("y", "en", "a rational description");
  dictionary.c("z", "en", "a magnitude limit");
  dictionary.c("á", "en", "a projection of an origin");
  dictionary.c("é", "en", "a projection of a representation");
  dictionary.c("í", "en", "a projection of a description");
  dictionary.c("ó", "en", "a projection of a definition");
  dictionary.c("ú", "en", "a rational projection");
  dictionary.c("ñ", "en", "an oscillating set of information");

  dictionary.c("A", "en", "an initial definition or origin");
  dictionary.c("B", "en", "conclusion");
  dictionary.c("C", "en", "a content or container");
  dictionary.c("D", "en", "a thought");
  dictionary.c("E", "en", "a representation");
  dictionary.c("F", "en", "the momentum of information");
  dictionary.c("G", "en", "the logarithmic magnitude of information");
  dictionary.c("H", "en", "within or between");
  dictionary.c("I", "en", "a description");
  dictionary.c("J", "en", "a link");
  dictionary.c("K", "en", "the divergence of information");
  dictionary.c("L", "en", "a direction");
  dictionary.c("M", "en", "the plurality");
  dictionary.c("N", "en", "a singular model or set");
  dictionary.c("O", "en", "a definition");
  dictionary.c("P", "en", "a projection");
  dictionary.c("Q", "en", "the previous");
  dictionary.c("R", "en", "an extension or radius");
  dictionary.c("S", "en", "oscillation");
  dictionary.c("T", "en", "what exists");
  dictionary.c("U", "en", "a rationalization");
  dictionary.c("V", "en", "a portion");
  dictionary.c("W", "en", "everything");
  dictionary.c("X", "en", "here");
  dictionary.c("Y", "en", "a rational description");
  dictionary.c("Z", "en", "a magnitude limit");
  dictionary.c("Á", "en", "a projection of an origin");
  dictionary.c("É", "en", "a projection of a representation");
  dictionary.c("Í", "en", "a projection of a description");
  dictionary.c("Ó", "en", "a projection of a definition");
  dictionary.c("Ú", "en", "a rational projection");
  dictionary.c("Ñ", "en", "an oscillating set of information");

};

export default createABZeusDict;
